services:
  # Memopad it self
  app:
    build: .
    container_name: memopad
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=memopad
      - PG_PASSWORD=memopad
      - PG_DATABASE=memopad
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=memopad
      - ES_PASSWORD=memopad
    depends_on:
      - postgres
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
  
  # Init service (configures Infrastructure)
  init-service:
    image: curlimages/curl:latest
    container_name: init-service
    restart: no
    depends_on:
      - connect
      - elasticsearch
      - postgres
    entrypoint: ["/bin/sh", "-c", "/scripts/infra-init.sh"]
    volumes:
      - ./scripts/infra-init.sh:/scripts/infra-init.sh


  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: memopad
      POSTGRES_PASSWORD: memopad
      POSTGRES_DB: memopad
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "memopad", "-d", "memopad"]
      interval: 5s
      timeout: 5s

  # Zookeeper for Kafka Coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # Kafka Connect with Debezium for Change Data Capture (CDC)
  connect:
    image: debezium/connect:3.0.0.Final
    container_name: kafka-connect
    restart: always
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
    ports:
      - "8083:8083"

  # Elasticsearch for Fuzzy Searching
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USER=memopad
      - ELASTIC_PASSWORD=memopad
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 5s
