services:
  # Memopad it self
  app:
    build: .
    #container_name: memopad
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=memopad
      - PG_PASSWORD=memopad
      - PG_DATABASE=memopad
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=memopad
      - ES_PASSWORD=memopad
    depends_on:
      - postgres
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
  
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    #container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: memopad
      POSTGRES_PASSWORD: memopad
      POSTGRES_DB: memopad
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "memopad", "-d", "memopad"]
      interval: 10s
      timeout: 10s

  # Elasticsearch for Fuzzy Searching
  # Currently unused
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    restart: always
    #container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USER=memopad
      - ELASTIC_PASSWORD=memopad
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 5s
