spring.datasource.url=jdbc:postgresql://postgres/memopad
spring.datasource.username=memopad
spring.datasource.password=memopad
server.forward-headers-strategy=framework
spring.datasource.hikari.maximum-pool-size=100
